POST https://scaling-space-goldfish-97699j6q445h9p9-8080.app.github.dev/api/v1/auth/signup HTTP/1.1
content-type: application/json

{
    "login": "mail2@mail.com",
    "password": "password",
    "role": "ADMIN"
}

###
POST https://scaling-space-goldfish-97699j6q445h9p9-8080.app.github.dev/api/v1/auth/signin HTTP/1.1
content-type: application/json

{
    "login": "mail2@mail.com",
    "password": "password"
}

POST https://scaling-space-goldfish-97699j6q445h9p9-8080.app.github.dev/users HTTP/1.1
content-type: application/json

{
    "name": "user1",
    "email": "mail@mail.com",
    "password": "password"
}

####

GET https://scaling-space-goldfish-97699j6q445h9p9-8080.app.github.dev/users HTTP/1.1
Accept: application/json

###
GET https://scaling-space-goldfish-97699j6q445h9p9-8080.app.github.dev/users/2 HTTP/1.1
Accept: application/json


###
DELETE https://scaling-space-goldfish-97699j6q445h9p9-8080.app.github.dev/users/2 HTTP/1.1
Accept: application/json